### Window rules
for_window [app_id="pavucontrol"] floating enable
for_window [app_id="org.gnome.Calculator"] floating enable
for_window [app_id="blueman-manager"] floating enable
for_window [title="^Open File$"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="dialog"] floating enable
for_window [window_type="dialog"] floating enable
