sell /usr/bin/zshrc

# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include ./themes/frappe.conf
# END_KITTY_THEME

# Remove Window Bar "x,-"
hide_window_decorations yes
# Add inside padding
window_padding_width 6
# Transparency
background_opacity 0.85
dynamic_background_opacity yes
background_blur 1

# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        9.0

